### PR TITLE
fix(ENG-3732): Remove manual confirmation when needing to alter table

### PR DESCRIPTION
**Pull request by CIII**
### WHY are these changes introduced?

Fixes [[ENG-3732](#url-here)] 

### WHAT is this pull request doing?

Remove manual confirmation when needing to alter table

## 

### How to Test

🖥 [Local development instructions](#link-to-repo-readme)
🗒 [General testing guidelines](#link-to-testing-guidelines)
📄 [Changelog guidelines](#link-to-changelog-guidelines)

### Testing checklist

* [ ] Tested on mobile
* [ ] Tested on multiple browsers
* [ ] Tested for accessibility
* [ ] Updated the `README.md` with documentation changes
* [ ] Updated public facing documentation

### CODE REVIEW

**Comment by syriak** [comment]
Can we just set `disableTTYConfirmation: true` in our client config instead of making these code changes?

**Comment by CIII** [comment]
> Can we just set `disableTTYConfirmation: true` in our client config instead of making these code changes?

Yep that's right however the ticket's intention was to remove this

**Review by syriak — APPROVED** [review]
Looks good to me, good call updating the README as well.

**Comment by ignacio-badiola** [comment]
I think that we're removing more code than needed. 
Also, I like the idea of using the options `disableTTYConfirmation: true`. I thought that this story was to ENABLE use that option in PRODUCTION since by default migration is set to `safe` in production

**Pull request closed without merging**
